media:
  - name: images
    label: Images
    input: assets/img
    output: /blog/assets/img
    categories: [ image ]
  - name: documents
    label: Documents
    input: assets/doc
    output: /blog/assets/doc
    categories: [ document ]
content:
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view:
      fields: [ title, date, categories ]
      sort: [ date, title ]
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: description
        label: Description (optional)
        type: string
      - name: image
        label: Image
        type: image
      - name: categories
        label: Categories
        type: select
        options:
          multiple: true
          creatable: true
          values: [ Prose, Characters, Worldbuilding, Affirmations, Essays, Poetry, Rants, Ilmaria ]
      - name: tags
        label: Tags
        type: select
        options:
          creatable: true
          multiple: true
          values: [ Bible, creature, death, depression, gender-dysphoria, grief, LGBTQIA+, prayer, school, taboo, templates, tips ]
      - name: body
        label: Body
        type: rich-text
  - name: config
    label: Jekyll config
    path: _config.yml
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provused for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)