title: un-Graphophobic
tagline: Write. Read. Be Free.
description: A place for me to write and think freely.
url: https://bravishkaskytano.github.io
baseurl: /blog
avatar: /blog/assets/img/logo.png
social_preview_image: /blog/assets/img/logo-full.png
