# bundle exec jekyll serve --livereload --baseurl=""
# This is the configuration file for the Jekyll site.
# It contains site-wide settings, plugins, and collections.
# For more information, see: https://jekyllrb.com/docs/configuration/
# For the GitHub Pages version, see: https://pages.github.com/
title: "The Worldweaver's Journal"
tagline: "A Chronicle of Realms and Imagination."
description: "Open the door to veil-thin worlds and dim-lit realms, where forgotten archives whisper stories lost to time. Here, shadows speak, memories stir, and every step leads deeper into the unseen. Let the echoes guide you—what was lost still lingers."
theme: null
author: "Yoela O"
url: https://bravishkaskytano.github.io
baseurl: "/blog"
paginate: 5
paginate_path: "/page:num/"
permalink: /:collection/:name/

logo: /assets/img/logo.jpg

# social:
#   name: Ben Balter
#   links:
#     - https://twitter.com/BenBalter
#     - https://www.facebook.com/ben.balter
#     - https://www.linkedin.com/in/BenBalter
#     - https://github.com/benbalter
#     - https://keybase.io/benbalter

markdown: kramdown

collections_dir: collections
collections:
  stories:
    output: true
  books:
    output: true
  characters:
    output: true
  worlds:
    output: true
  magic:
    output: true
  societies:
    output: true
  cultures:
    output: true
  geography:
    output: true
  creatures:
    output: true
  history:
    output: true

defaults:
  - scope:
      path: ""
      type: stories
    values:
      layout: story
  - scope:
      path: ""
      type: books
    values:
      layout: book
  - scope:
      path: ""
      type: characters
    values:
      layout: character
  - scope:
      path: ""
      type: worlds
    values:
      layout: world
  - scope:
      path: ""
      type: magic
    values:
      layout: magic
  - scope:
      path: ""
      type: societies
    values:
      layout: society
  - scope:
      path: ""
      type: cultures
    values:
      layout: culture
  - scope:
      path: ""
      type: geography
    values:
      layout: geography
  - scope:
      path: ""
      type: creatures
    values:
      layout: creature
  - scope:
      path: ""
      type: history
    values:
      layout: history

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
