title: "un-Graphophobic"

logo: "/assets/img/background.png"
favicon_ico: "/assets/favicons/favicon.ico"

# You may need to change the base URL depending on your deploy configuration.
baseurl: ""

permalink: pretty

defaults:
  - scope:
      path: garden
    values:
      layout: note
  - scope:
      path: "**/*"
    values:
      layout: default

plugins:
  - jekyll-last-modified-at
  - jekyll-wikirefs

wikilinks:
  attributes:
    enabled: true
  css:
    exclude: ["footnote", "reversefootnote"]
    name:
      typed: "typed"
      wiki: "wiki-link"
      web: "web-link"
      invalid_wiki: "invalid-wiki-link"
      embed_container: "embed-container"
      embed_title: "embed-title"
      embed_content: "embed-content"
      embed_link: "embed-wiki-link"
      embed_image_container: "embed-image-container"
      embed_image: "embed-image"
  enabled: true
  exclude: []

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  # site specific
  - .foam/
  - .vscode/
  - .stfolder/
  - .markdownlint.json
  - collections/.trash/
  - collections/.obsidian/
