title: un-Graphophobic
author: Bravishka Skytano
description: >- # this means to ignore newlines until "baseurl:"
  A place to open up and share my mind.
url: "https://aspiring-writer.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

background: "/assets/images/background.png"
avatar: "https://www.gravatar.com/avatar/8305681be23372ec3c774233546f849f.jpg?s=200"
start: 2020
current: 2023

# Build settings
permalink: none
future: false
keep_files:
  - assets/images
  - assets/favicons

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      #excerpt_separator: <!-- more -->

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

related_by: categories
related_limit: 6
related_categories: 1
related_tags: 1

#diff_blog: "q7f864hffi8m218eaq6d623sezfgkz1vzfva4oxjeyxq9l2dwp"

#utterances:
  #repo: Aspiring-Writer/aspiring-writer.github.io # Github repository owner and name
  # Available values: pathname | url | title | og:title
  #issue_term: pathname
  # Available values: github-light | github-dark | preferred-color-scheme | github-dark-orange | icy-dark | dark-blue | photon-dark | boxy-light
  #theme: preferred-color-scheme

# Exclude from processing.cd
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
