# bundle exec jekyll serve --livereload --baseurl=""
# This is the configuration file for the Jekyll site.
# It contains site-wide settings, plugins, and collections.
# For more information, see: https://jekyllrb.com/docs/configuration/
# For the GitHub Pages version, see: https://pages.github.com/
title: "Echoes of Elsewhere"
tagline: "Where distant worlds whisper back."
description: "Open the door to veil-thin worlds and dim-lit realms, where forgotten archives whisper stories lost to time. Here, shadows speak, memories stir, and every step leads deeper into the unseen. Let the echoes guide you—what was lost still lingers."
author: "Yoela O"
url: https://bravishkaskytano.github.io
baseurl: "/blog"
paginate: 5
paginate_path: "/page:num"
permalink: none #/:categories/:title:output_ext

logo: /assets/img/logo.jpg

characters_desc:
locations_desc:

#
# Jekyll configurations
#

# You can customize it changing default layout for all pages
# More info: https://jekyllrb.com/docs/configuration/
#
# git-wiki includes some internal themes that you can choose
# check _layouts folder
#
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed

collections_dir: collections
collections:
  books:
    output: true
    permalink: /books/:path
  characters:
    output: true
    permalink: /characters/:path
  locations:
    output: true
    permalink: /locations/:path
  species:
    output: true
    permalink: /species/:path

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      path: ""
      type: "books"
    values:
      layout: "chapter"
  - scope:
      path: ""
      type: "characters"
    values:
      layout: "character"
  - scope:
      path: ""
      type: "locations"
    values:
      layout: "location"
  - scope:
      path: ""
      type: "species"
    values:
      layout: "species"

plugins:
  - jekyll-avatar
  - jekyll-coffeescript
  - jekyll-feed
  - jekyll-paginate
  - jekyll-optional-front-matter
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
