title: un-Graphophobic
author: Bravishka Skytano
description: >- # this means to ignore newlines until "baseurl:"
  A place to open up and share my mind.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aspiring-writer.github.io" # the base hostname & protocol for your site, e.g. http://example.com

logo: "/assets/favicons/favicon-32x32.png"
avatar: "https://www.gravatar.com/avatar/8305681be23372ec3c774233546f849f.jpg?s=200"
bio: "Christian. Programmer. Student. Aspiring Writer."
location: "Somewhere in the USA"
start: 2019

# Build settings
permalink: /:collection/:slugified_categories/:title/
collections_dir: collections
collections:
  books:
    output: true
    permalink: /:collection/:path/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: <!-- more -->
  -
    scope:
      path: "collections/_books"
    values:
      layout: chapter

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-postcss
  - jekyll-paginate-v2
  - jekyll-avatar
  - jekyll-sitemap
 
postcss:
  cache: false

pagination:
  enabled: true
  per_page: 25
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
  title: ':title - page :num of :max' # optional
  sort_field: 'date'
  trail:
    before: 2
    after: 2

diff_blog: "q7f864hffi8m218eaq6d623sezfgkz1vzfva4oxjeyxq9l2dwp"

utterances:
  repo: Aspiring-Writer/aspiring-writer.github.io # Github repository owner and name
  # Available values: pathname | url | title | og:title
  issue_term: pathname
  # Available values: github-light | github-dark | preferred-color-scheme | github-dark-orange | icy-dark | dark-blue | photon-dark | boxy-light
  theme: dark-blue

# Exclude from processing.cd
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
