title: "un-Graphophobic"

logo: "/assets/img/background.png"
favicon_ico: "/assets/favicons/favicon.ico"

# You may need to change the base URL depending on your deploy configuration.
baseurl: ""

permalink: none

defaults:
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: garden
    values:
      layout: note
      pinned: false
  - scope:
      path: "**/*"
    values:
      layout: default

plugins:
  - jekyll-last-modified-at
  #- jekyll-wikirefs
  #- jekyll-graph

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  # site specific
  - .foam/
  - .vscode/
  - .stfolder/
  - .markdownlint.json
  - .trash/
  - .obsidian/
