title: un-Graphophobia
description: >- # this means to ignore newlines until "baseurl:"
  A place to open up and share my mind.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aspiring-writer.github.io" # the base hostname & protocol for your site, e.g. http://example.com

location: "Somewhere in the USA"
gravatar: "yolson@liberty.edu"
bio: "Christian. Programmer. Student. Aspiring Writer."

diff_blog: "q7f864hffi8m218eaq6d623sezfgkz1vzfva4oxjeyxq9l2dwp"

utterances:
  repo: Aspiring-Writer/aspiring-writer.github.io # Github repository owner and name
  # Available values: pathname | url | title | og:title
  issue_term: pathname
  # Available values: github-light | github-dark | preferred-color-scheme | github-dark-orange | icy-dark | dark-blue | photon-dark | boxy-light
  theme: preferred-color-scheme

# Build settings
remote_theme: Aspiring-Writer/jekyll-papercss-theme
paginate: 10
permalink: none
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: <!-- more -->
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  
# Exclude from processing.cd
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
