baseURL: "https://ungraphophobic.netlify.app/"
title: "un-Graphophobic"
theme: "kaleidoscope"

avatar: "https://www.gravatar.com/avatar/8305681be23372ec3c774233546f849f.jpg?s=200"

params:
  mainSections: ['posts']
  author: "Yoela O."
  favicon: "/favicon.ico"
  site_logo: ""
  description: "A place where I can be free."
  featured_posts: false
  
  # choose fonts from
  main_font: "georgia"
  title_font: "garamond"
  header_font: "garamond"

# https://gohugo.io/content-management/menus/
menu:
  main:
  - 
    name: About
    pageRef: /about
    weight: 10
  - 
    name: Posts
    pageRef: /posts
    weight: 20
  - 
    name: Categories
    pageRef: /categories
    weight: 30
  - 
    name: Tags
    pageRef: /tags
    weight: 40
  - 
    name: Notes
    params:
      rel: external
    pre: <i class="fa fa-heart"></i>
    url: https://vsdigitalgarden.vercel.app/
    weight: 50

  footer:
  - 
    name: Github
    params:
      rel: external
    pre: <i class="fa-brands fa-github"></i>
    url: https://github.com/BravishkaSkytano
    weight: 10
  -
    name: Reddit
    params:
      rel: external
    pre: <i class="fa-brands fa-reddit-alien"></i>
    url: https://www.reddit.com/user/Y_Mystake_O
    weight: 20
  -
    name: LinkedIn
    params:
      rel: external
    pre: <i class="fa-brands fa-linkedin-in"></i>
    url: https://www.linkedin.com/in/yoela-o
    weight: 30

enableGitInfo: true
frontmatter:
  date: ["date", "publishDate", "lastmod"]
  lastmod: ["lastmod", ":git", "date", "publishDate"]

related:
  includeNewer: true
  threshold: 0
  toLower: false
  indices:
    -
      name: 'categories'
      weight: 100
    -
      name: 'tags'
      weight: 50
    -
      name: 'date'
      weight: 10
